name: Toolbox
main: de.disposed.bukkit.toolbox.ToolboxPlugin
version: 1.2b
website: http://www.eikefoken.de
author: sturmkeyser
description: Toolbox for duplicating and painting blocks
commands:
  clear:
    description: Clears your inventory
    usage: |
           /<command> [all|main|bar]
  compact:
    description: Compacts your inventory
    usage: |
           /<command>
  more:
    aliases: [m]
    description: Gives you more of the item in your hand
    usage: |
           /<command> [stacks]  
  pick:
    aliases: [p]
    description: Sets the data value of the item in your hand
    usage: |
           /<command> <value>
  mimic:
    aliases: [p]
    description: Matches your inventory to types of blocks around you
    usage: |
           /<command> [radius]
  duplicator:
    aliases: [duper]
    description: Gives you the duplicator tool
    usage: |
           /<command> 
  paintbrush:
    aliases: [painter]
    description: Gives you the paintbrush tool
    usage: |
           /<command>
  datawrench:
    aliases: [scroller]
    description: Gives you the data scroller tool
    usage: |
           /<command>
  tools:
    description: Gives you the duplicator, data scroller and paintbrush tools
    usage: |
           /<command>
  tbreload:
    description: Reloads the configuration file
    usage: |
           /<command>